### ISSUE TITLE
Enhancement: Support for debugging individual scenarios

### ISSUE THREAD

**Issue by clmcdonald** [kirksl/karate-runner#25]
I love the plugin, and thanks for your work on it. One enhancement that I would like to request is the ability to debug individual scenarios. I can run scenarios on their own, but as far as I know the only way to use breakpoints is to debug the entire feature file. If I have a bunch of long-running scenarios in a feature file, it could potentially make it tough to debug what I want.

**Comment by ptrthomas** [comment]
@clmcdonald yes, agree. just FYI - you can add additional debug "sections" to the `launch.json`

so I just tried this and it worked, since Karate can run a feature at a given line number if you append `:30` where 30 is the line number and where a `Scenario` or even an `Examples` row is present.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/915480/76005939-bef53a80-5f31-11ea-91e5-50e7463eae82.png">

@kirksl maybe we can connect a code-lens action called `Debug` to do this ?

**Comment by ptrthomas** [comment]
@clmcdonald by the way, the above approach gets super interesting, because you can actually debug even a parallel run ! you can add a `-T 5` in the `karateOptions` IIRC

Another workaround I can suggest for now which may be better than the `:linenum` hack, is to create a new `Feature` maybe with a `@ignore` tag on it that does something like this:

`* call read('some.feature:15')`

and that should work !

**Comment by kirksl** [comment]
@clmcdonald @ptrthomas fixed.  there are now two codelens hyperlinks.  when you click a codelens for a feature the whole file will be debugged.  when you click a codelens for a scenario or scenario outline only it will be debugged.  if you click the "start debugging" play button in the debugger view built into vscode the whole file will be debugged.  https://github.com/kirksl/karate-runner/commit/9c8b42d08282754d7948be82c4c9fafef70400c1

**Comment by ptrthomas** [comment]
@kirksl this is great, love how the `Debug` options becomes so much more "accessible".
