### ISSUE TITLE
Debug code lens is using parent maven project

### ISSUE THREAD

**Issue by clmcdonald** [kirksl/karate-runner#27]
I have a folder called test-suite with its own pom.xml that adds Karate as a dependency. When I use the "Run Karate Tests" code lens, it works as expected. However, with the new Debug code lens, it is trying to run the tests from the parent pom.xml, and therefore I get the error: "java.lang.ClassNotFoundException: com.intuit.karate.cli.Main". One workaround I've found is to open up only the test-suite folder in VSCode. Previously I had opened up the entire project. If I open up just the test-suite folder, it works as expected.

Clicking "start debugging" in the top menu is still working.

**Comment by kirksl** [comment]
@clmcdonald thanks for all the feedback.  i'm suspecting this is happening because the path to the pom.xml in our debug configurations are not a fully qualified path and when we run "karate: run" the pom.xml is fully qualified.
![image](https://user-images.githubusercontent.com/24948266/76262997-0bcf5e80-621b-11ea-9b78-bcf690dc2290.png)

if possible it would be helpful if you can provide a sample project that reproduces the issue.

**Comment by clmcdonald** [comment]
Yes, fully qualifying the pom.xml in my "karateCli" launch configuration did solve the problem

**Comment by kirksl** [comment]
@clmcdonald fixed.  please remove the .vscode directory at the root of your project, restart vscode, setup your karate debug configurations and try again.  we are now dynamically setting the correct path to your pom.xml or build.gradle.  https://github.com/kirksl/karate-runner/pull/28/commits/7e1f0f24259cbcddeaf296790f32c5aa08450caa
