### ISSUE TITLE
"no tests were executed" when using runner

### ISSUE THREAD

**Issue by dwwhalen** [kirksl/karate-runner#32]
First of all, sorry for what I'm sure is a basic question.  

I have created a new project using the Karate Maven archetype, version 0.9.5.  I have VS Code version 1.43.2 running on a Macbook.  I can run the user.feature test with no problem when using `mvn clean test`.

I want the run this same test with the Karate Runner (0.8.3).  When I try to run it with the runner I accept the default Karate Runner (_SyncRunner) and I get:
`failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project myproject: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)`

The generated command line is:
`mvn clean test -f "/Users/denniswhalen/myproject/pom.xml" -Dtest=_SyncRunner -Dkarate.options="/Users/denniswhalen/myproject/src/test/java/examples/users/users.feature:7"`

Any help would be appreciated.  Thanks.

**Comment by kirksl** [comment]
@dwwhalen hello.  i suspect you may need to change _SyncRunner to the actual name of the Java file serving as your 'Karate Runner' which runs your feature file.  eg.  here you'd specify DemoTest instead of _SyncRunner --> https://github.com/intuit/karate/blob/master/karate-demo/src/test/java/demo/DemoTest.java

**Comment by dwwhalen** [comment]
That's it, thank you!
