### ISSUE TITLE
wrapper implementation assumes wrapper are in the path

### ISSUE THREAD

**Issue by maxandersen** [kirksl/karate-runner#56]
Thanks for #54, but the fix does not seem right.

it seems to just use `gradlew` instead of `gradle` and thus assumes `gradlew` is on the path.

It is not, it needs to be located by traversing upwards the directory hiearchy from the feature file until you find the nearest ./gradlew.

This file would be next to build.gradle thus I suggest when you detect wether calling mvn or gradle check if the wrapper files are present and use the absolute paths instead.

otherwise I don't see how this can work - thanks again!

**Comment by maxandersen** [comment]
note, I did find a way to work around it for now - install https://github.com/dougborg/gdub and `ln -s gw gradlew` then it will figure out the right gradle to use.

works but not exactly great ;)

**Comment by kirksl** [comment]
@maxandersen replicated the issue.  works on windows, but mac/linux apparently require a "./" in front of "gradlew" or "mvnw".  i'll work on fixing this.  fyi we do traverse backwards from the feature file(s) you call until we reach either a pom.xml or build.gradle and use that as the folder we execute maven/gradle from.

**Comment by kirksl** [comment]
@maxandersen please confirm if this fixed it for you.  https://github.com/kirksl/karate-runner/commit/388b0d6e1189d98a7743ddf15551bb93366ab772

**Comment by maxandersen** [comment]
just saw this - checking...

**Comment by maxandersen** [comment]
Yes, now it calls ./gradlew and things work better.

Now I'm just curious how to actually run the tests with current working directory being where the *.feature files are - in my case they are not part of the main java project but external features used to test the produce cli ...thus I kept it simple and don't require any mvn/gradle invocation.

any way to configure how karate is run (i.e. which command not just arguments)  and can the current working dir be the same as the feature file ?

**Comment by maxandersen** [comment]
one thing that is still a bit annoying is that it uses ./mvnw even when the project don't have a ./mvnw file. 

Any chance the extension can just detect wether its present or not ?

**Comment by kirksl** [comment]
can you tell me what happens when you try to run the tests with the current working directory being where the feature files are.  ultimately this extension doesn't care what the working directory is.  when you tell it to run a feature file it will start searching within that directory and then all parent directories if it has to until it finds either a pom.xml or build.gradle file.  once found it will run maven if pom.xml was found, and if not found it will run gradle if build.gradle was found.

regarding configuring karate if you can configure it to run a specific way to run from the command line without this extension that it is possible to configure this extension the same way.  some things are hardcoded for convenience so it will depend on exactly what you're trying to do.  i would say, get it to work on the command line first the way you need it and we can explore if the extension can do it.

regarding detection of maven/gradle wrappers existing and calling mvnw/gradlew or mvn/gradle.  admittedly we've tried to keep this extension simple and avoid heavily integrating logic that is dependent on external tools if possible.  the more things we try to babysit the more code management required as those external tools change.  we additionally for those reasons don't check if maven/gradle are installed, java, scala or anything else that the build system and user should ultimately make sure are present.  i do see calling mvn vs mvnw or gradle vs gradlew a little more trivial though, but i think in that case people are typically using one or the other and can simply choose to switch it on or off in the extension.  maybe if we get enough votes we'll consider it though.

**Comment by kirksl** [comment]
@maxandersen closing this out as this is generally solved.  please open a new ticket if there's anything else still interesting to solve.
