### ISSUE TITLE
issue about standalone karate jar  and karate-runner

### ISSUE THREAD

**Issue by vista3344** [kirksl/karate-runner#88]
I use karate standalone jar release in vscode with karate-runner, windows 10
First, I put karate jar and batch file in the root path of vscode workspace, codelens works very well;
Then I move these karate release files to another folder , and  add this path to system environment variable - path (no cannot approach class error);
Finally, codelens of running test does not response to click; debugging test will lead to permanent waiting till timeout, although server started with log in output window;
But if I creat one empty file called karate.jar in workspace root path , both codelens will work. So strange .

**Comment by kirksl** [comment]
@vista3344 yes this is a hard limitation with the plugin for now.  This aligns with pom.xml and build.gradle needing to be at the root of projects to signal Maven or Gradle is in use.  Backlogging this for now and we'll definitely revisit this if we can elegantly solve this.  Not sure what to make of the empty karate.jar file, it definitely tricks the extension and guessing it still works due to native Java classpath mechanisms.
